// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package bd_portal_bi

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bi struct {
	ID      int32
	Link    pgtype.Text
	IDSetor pgtype.Int4
}

type Permisao struct {
	ID   int32
	Nome pgtype.Text
}

type Setor struct {
	ID    int32
	Setor string
}

type Usuario struct {
	ID         int32
	Nome       pgtype.Text
	IDSetor    pgtype.Int4
	IDPermisao pgtype.Int4
	Email      pgtype.Text
	Login      pgtype.Text
	Senha      pgtype.Text
}
